//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ŀ�����Ǳ�
//  @ File Name : CoffeeMachine.java
//  @ Date : 2016-06-14
//  @ Author : 
//
//



package exmachine;

import java.util.Scanner;

public class CoffeeMachine extends Jego {
	private static int COFFEE = 200;
	private int creameCoffee = 0;
	private int blackCoffee = 0;
	private int hongcha = 0;
	private int jandon = 0;
	private int password = 1111;
	public CoffeeMachine() {
		System.out.println("Cafe");
	}
	public void coffeeDisp() {
		while(true){
		Scanner sc = new Scanner(System.in);
		System.out.println("동전을 입력하세요: ");
		int money = sc.nextInt();
		if (money >= COFFEE){
			super.setMoney(money);
			System.out.println("자판기 토탈: " + super.getMoney());
		}else{
			System.out.println("금액이 부족합니다\n"); 
			continue;
		}	
		System.out.println("\n커피 종류를 선택하세요: \n(1. 블랙, 2. 크림)");
		int choice = sc.nextInt();
		switch(choice){
			case 1 : System.out.println("블랙을 선택하셨습니다 \n"); break;
			case 2 : System.out.println("크림을 선택하셨습니다 \n"); break;
			default : System.out.println("틀렸습니다 \n"); continue;
		}
		System.out.println("몇잔을 드릴까요: ");
		int cupCount = sc.nextInt();
		if(cupCount > super.getCup()){
			System.out.println("현재 주문 가능하신 잔 수: " + super.getCup() + "\n");
			continue;
		}
		calc(money, choice, cupCount);
			if(choice == 1){
				System.out.println("블랙커피 " + cupCount + "잔 , 잔돈: " + jandon);
				if(super.getBlack() < cupCount){
					System.out.println("블랙커피는 품절, 홍차로 드립니다 " + cupCount + "잔 , 잔돈: " + jandon);	
				}
			}else{
				System.out.println("홍차 " + cupCount + "잔 , 잔돈: " + jandon);
			}
			
			
		break;
		}
	}
	
	private void calc(int money, int choice, int cupCount) {
		jandon = money - (cupCount * COFFEE);
		
		
	}
}















