//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ŀ�����Ǳ�
//  @ File Name : Manager.java
//  @ Date : 2016-06-14
//  @ Author : 
//
//



package exmachine;


public class Manager {
	private int password = 1111;
	
	public void jego() {
	
		Jego jego = new Jego();
		
	}
}	
