//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Ŀ�����Ǳ�
//  @ File Name : User.java
//  @ Date : 2016-06-14
//  @ Author : 
//
//



package exmachine;


public class User {
	public static void main(String[] args) {
		CoffeeMachine bb = new CoffeeMachine();
		bb.coffeeDisp();
		
	}
}
